/* Automatically generated by './build/bin/build-entry.js' */
import Affirm from '../packages/affirm/index.js';
import Alert from '../packages/alert/index.js';
import Avatar from '../packages/avatar/index.js';
import Backtop from '../packages/backtop/index.js';
import Badge from '../packages/badge/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import Button from '../packages/button/index.js';
import TextButton from '../packages/text-button/index.js';
import LinkButton from '../packages/link-button/index.js';
import Calendar from '../packages/calendar/index.js';
import CancelButton from '../packages/cancel-button/index.js';
import Card from '../packages/card/index.js';
import Cascader from '../packages/cascader/index.js';
import Checkbox from '../packages/checkbox/index.js';
import Checkboxes from '../packages/checkboxes/index.js';
import Collapse from '../packages/collapse/index.js';
import ColorPicker from '../packages/color-picker/index.js';
import DatePicker from '../packages/date-picker/index.js';
import DateTimePicker from '../packages/date-time-picker/index.js';
import Dialog from '../packages/dialog/index.js';
import Divider from '../packages/divider/index.js';
import Drawer from '../packages/drawer/index.js';
import Dropdown from '../packages/dropdown/index.js';
import Form from '../packages/form/index.js';
import Image from '../packages/image/index.js';
import Input from '../packages/input/index.js';
import InputNumber from '../packages/input-number/index.js';
import InputLimitNumber from '../packages/input-limit-number/index.js';
import Link from '../packages/link/index.js';
import ListCard from '../packages/list-card/index.js';
import Menu from '../packages/menu/index.js';
import PageHeader from '../packages/page-header/index.js';
import Pagination from '../packages/pagination/index.js';
import Popconfirm from '../packages/popconfirm/index.js';
import Popover from '../packages/popover/index.js';
import Progress from '../packages/progress/index.js';
import Radio from '../packages/radio/index.js';
import Rate from '../packages/rate/index.js';
import SearchForm from '../packages/search-form/index.js';
import Select from '../packages/select/index.js';
import Slider from '../packages/slider/index.js';
import Steps from '../packages/steps/index.js';
import Switch from '../packages/switch/index.js';
import Table from '../packages/table/index.js';
import Tabs from '../packages/tabs/index.js';
import Tag from '../packages/tag/index.js';
import TimePicker from '../packages/time-picker/index.js';
import Timeline from '../packages/timeline/index.js';
import Tip from '../packages/tip/index.js';
import Tooltip from '../packages/tooltip/index.js';
import Transfer from '../packages/transfer/index.js';
import Tree from '../packages/tree/index.js';
import Upload from '../packages/upload/index.js';

import {ACTIONS_KEY_MAP} from './constants/actionsMap'
import './assets/scss/common.scss'
import './assets/iconfont/iconfont.css'

const components = [
  Pagination,
  Dialog,
  Dropdown,
  Menu,
  ListCard,
  SearchForm,
  Input,
  InputNumber,
  InputLimitNumber,
  Radio,
  CancelButton,
  DateTimePicker,
  Checkbox,
  Checkboxes,
  Switch,
  Select,
  Option,
  Button,
  TextButton,
  LinkButton,
  Table,
  DatePicker,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  Form,
  Tabs,
  Tag,
  Tree,
  Alert,
  Slider,
  Upload,
  Progress,
  Badge,
  Card,
  Rate,
  Steps,
  Collapse,
  Cascader,
  ColorPicker,
  Transfer,
  Timeline,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  PageHeader,
  Avatar,
  Drawer,
  Popconfirm,
];

const install = function(Vue) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$Affirm = Affirm;
  Vue.prototype.$Tip = Tip;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.15.0',
  install,
  Pagination,
  Dialog,
  Dropdown,
  Menu,
  ListCard,
  SearchForm,
  Input,
  InputNumber,
  InputLimitNumber,
  Radio,
  CancelButton,
  DateTimePicker,
  Checkbox,
  Checkboxes,
  Switch,
  Select,
  Option,
  Button,
  TextButton,
  Table,
  DatePicker,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  Form,
  Tabs,
  Tag,
  Tree,
  Alert,
  Slider,
  Upload,
  Progress,
  Badge,
  Card,
  Rate,
  Steps,
  Collapse,
  Cascader,
  LinkButton,
  ColorPicker,
  Transfer,
  Timeline,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  PageHeader,
  Avatar,
  Drawer,
  Popconfirm,
  ACTIONS_KEY_MAP
};
